permalink: '/:categories/:year/:month/:day/:title'

exclude:
- '.rvmrc'
- '.rbenv-version'
- 'README.md'
- 'Rakefile'
- 'changelog.md'
- 'Gemfile'
- 'Gemfile.lock'
- 'package.json'
- 'package-lock.json'
- 'node_modules'
- 'scripts'

excerpt_separator: '<!--more-->'

title: 'Jan Krems'
tagline: ''
author:
  name: 'Jan Krems'
  email: 'jan.krems@gmail.com'
  github: 'jkrems'
  twitter: 'jankrems'

production_url: 'https://jkrems.dev'
